In [1]:
import numpy as np

In [5]:
list1 = [10, 20, 30]
list1

[10, 20, 30]

In [9]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [7]:
list2 = [30, 40, 50]
list2

[30, 40, 50]

In [10]:
list3 = [list1, list2]
list3

[[10, 20, 30], [30, 40, 50]]

In [11]:
arr2 = np.array(list3)
arr2

array([[10, 20, 30],
       [30, 40, 50]])

In [4]:
arr3 = np.arange(10, 20, 2)
arr3

array([10, 12, 14, 16, 18])

### Martrix Operations

In [14]:
list1

[10, 20, 30]

In [15]:
list1 * 3

[10, 20, 30, 10, 20, 30, 10, 20, 30]

In [17]:
arr2 * 3

array([[ 30,  60,  90],
       [ 90, 120, 150]])

### Lab

Create ndarrays of the following sizes:
1. One dimensional array with 12 elements (12,)
1. Two dimensional array of size (3,4)
1. Three dimensional array of size (2, 5, 4) 

In [19]:
a1 = np.arange(1, 13, 1)
a1.shape

(12,)

In [21]:
a2 = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [8, 9, 10, 11]])
a2.shape

(3, 4)

In [23]:
a3 = np.array(
    [
        [[1, 2, 3, 4], [4, 5, 6, 7], [8, 9, 10, 11], [1, 2, 3, 4], [4, 5, 6, 7]],
        [[4, 5, 6, 7], [8, 9, 10, 11], [1, 2, 3, 4], [4, 5, 6, 7], [8, 9, 10, 11]]
    ])
a3.shape

(2, 5, 4)

In [25]:
np.zeros((12,))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.ones((2, 5, 4), dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [34]:
arr2

array([[10, 20, 30],
       [30, 40, 50]])

In [36]:
arr2[0][2]

30

In [37]:
arr2[0, 2]

30

In [38]:
arr2[:,1]

array([20, 40])

In [39]:
a3

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 1,  2,  3,  4],
        [ 4,  5,  6,  7]],

       [[ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [40]:
a3[:,:,1]

array([[2, 5, 9, 2, 5],
       [5, 9, 2, 5, 9]])